Input:
- key: comp_status
  name: Component status
  description: Component status
  value:
    type: choice
    default: Enabled
    choices:
    - Enabled
    - Disabled
    units: '-'
- key: in_directory
  name: Input directory
  description: Input directory
  value:
    type: string
    default: /home/csdms/models/topoflow/3.1/share/data/treynor_iowa/
    units: '-'
- key: out_directory
  name: Output directory
  description: Output directory
  value:
    type: string
    default: ~/CMT_Output/
    units: '-'
- key: site_prefix
  name: Site prefix
  description: File prefix for the study site
  value:
    type: string
    default: Treynor
    units: '-'
- key: case_prefix
  name: Case prefix
  description: File prefix for the model scenario
  value:
    type: string
    default: Case5
    units: '-'
- key: n_steps
  name: Number of steps
  description: Number of time steps
  value:
    type: long
    default: '10'
    range:
      min: '1'
      max: 1e7
    units: '-'
- key: n_layers
  name: Number of soil layers
  description: Number of soil layers
  value:
    type: int
    default: '1'
    range:
      min: '1'
      max: '3'
    units: '-'
- key: dt
  name: Time step
  description: Timestep for infiltration process
  value:
    type: float
    default: '60.000'
    range:
      min: '0'
      max: 1e3
    units: sec
Layer 1:
- key: Ks_type_0
  name: K_sat type
  description: Allowed input types
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
- key: Ks_0
  name: K_sat
  description: Sat. hydraulic conductivity
  value:
    type: float
    default: '0.00000720'
    range:
      min: '0.0'
      max: 1e-2
    units: m/s
- key: Ki_type_0
  name: K_init type
  description: Allowed input types
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
- key: Ki_0
  name: K_init
  description: Init. hydraulic conductivity (< k_sat)
  value:
    type: float
    default: '0.00000010'
    range:
      min: '0.0'
      max: 1e-2
    units: m/s
- key: qs_type_0
  name: theta_sat type
  description: Allowed input types
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
- key: qs_0
  name: theta_sat
  description: Sat. soil water content
  value:
    type: float
    default: '0.48500000'
    range:
      min: '0.0'
      max: '1.0'
    units: '-'
- key: qi_type_0
  name: theta_init type
  description: Allowed input types
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
- key: qi_0
  name: theta_init
  description: Init. soil water content (< theta_sat)
  value:
    type: float
    default: '0.37580763'
    range:
      min: '0.0'
      max: '1.0'
    units: '-'
- key: G_type_0
  name: G type
  description: Allowed input types
  value:
    type: choice
    default: Scalar
    choices:
    - Scalar
    - Grid
    - Time_Series
    - Grid_Sequence
    units: '-'
- key: G_0
  name: G
  description: Capillary length scale
  value:
    type: float
    default: '0.72400000'
    range:
      min: '0.0'
      max: 1e2
    units: m
- key: soil_type_0
  name: Closest soil_type
  description: Closest standard soil type
  value:
    type: choice
    default: silty_loam
    choices:
    - sand
    - loamy_sand
    - sandy_loam
    - silty_loam
    - loam
    - sandy_clay_loam
    - silty_clay_loam
    - clay_loam
    - sandy_clay
    - silty_clay
    - clay
    units: '-'
Output:
- key: save_grid_dt
  name: Save grid timestep
  description: Time interval between saved grids
  value:
    type: float
    default: '60.000'
    range:
      min: '0.0'
      max: 1e6
    units: sec
- key: SAVE_V0_GRIDS
  name: Save v0 grids toggle
  description: Option to save grids of infil. rate (at surf)
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
    units: '-'
- key: v0_gs_file
  name: Save v0 grids file
  description: Filename for grid stack of v0
  value:
    type: string
    default: '[case_prefix]_2D-v0.nc'
    units: m/s
- key: SAVE_I_GRIDS
  name: Save I  grids toggle
  description: Option to save grids of cumul. infil. depth
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
    units: '-'
- key: I_gs_file
  name: Save I  grids file
  description: Filename for grid stack of i
  value:
    type: string
    default: '[case_prefix]_2D-I.nc'
    units: m
- key: save_pixels_dt
  name: Save pixels timestep
  description: Time interval between time series values
  value:
    type: float
    default: '60.000'
    range:
      min: '0.0'
      max: 1e6
    units: sec
- key: pixel_file
  name: Monitored pixel file
  description: Filename for monitored pixel file
  value:
    type: string
    default: '[case_prefix]_outlets.txt'
    units: '-'
- key: SAVE_V0_PIXELS
  name: Save v0 pixels toggle
  description: Option to save time series of infil. rate (at surf)
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
    units: '-'
- key: v0_ts_file
  name: Save v0 pixels file
  description: Filename for time series of v0
  value:
    type: string
    default: '[case_prefix]_0D-v0.txt'
    units: m/s
- key: SAVE_I_PIXELS
  name: Save I  pixels toggle
  description: Option to save time series of cumul. infil. depth
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
    units: '-'
- key: I_ts_file
  name: Save I  pixels file
  description: Filename for time series of i
  value:
    type: string
    default: '[case_prefix]_0D-I.txt'
    units: m
About:
- key: ModelName
  name: Model name
  description: Name of the model
  value:
    type: String
    default: InfilGreenAmpt
    units: '-'
- key: ModelAuthor
  name: Author name
  description: Name of the model author
  value:
    type: String
    default: 'Scott D. Peckham '
    units: '-'
- key: HTML_HELP_FILE
  name: HTML help file
  description: Url for html help file
  value:
    type: String
    default: http://csdms.colorado.edu/wiki/Model_help:TopoFlow-Infiltration-Green-Ampt
    units: '-'
