Input 1:
- key: comp_status
  name: Component status
  description: Component status
  value:
    type: choice
    default: Enabled
    choices:
    - Enabled
    - Disabled
    units: '-'
- key: in_directory
  name: Input directory
  description: Input directory
  value:
    type: string
    default: /home/csdms/models/topoflow/3.1/share/data/treynor_iowa/
    units: '-'
- key: out_directory
  name: Output directory
  description: Output directory
  value:
    type: string
    default: ~/CMT_Output/
    units: '-'
- key: site_prefix
  name: Site prefix
  description: File prefix for the study site
  value:
    type: string
    default: Treynor
    units: '-'
- key: case_prefix
  name: Case prefix
  description: File prefix for the model scenario
  value:
    type: string
    default: Case5
    units: '-'
- key: n_steps
  name: Number of steps
  description: Number of time steps for simulation
  value:
    type: int
    default: '10'
    range:
      min: '0.0'
      max: 1e7
    units: '-'
- key: dt
  name: Time step
  description: Ice process timestep
  value:
    type: float
    default: '0.1'
    range:
      min: '0'
      max: '100'
    units: years
- key: dt_max
  name: Max timestep
  description: Max timestep
  value:
    type: float
    default: '0.4'
    range:
      min: '0.0'
      max: '100'
    units: years
- key: t_max
  name: Max simulation time
  description: Max time to simulate
  value:
    type: float
    default: '100000'
    range:
      min: '0.0'
      max: 1e7
    units: years
Input 2:
- key: DEM_file
  name: DEM file
  description: Binary file containing a dem
  value:
    type: string
    default: '[site_prefix]_DEM.rtg'
    units: m
- key: H0_file
  name: Init. ice depth file
  description: Binary file containing initial ice depth
  value:
    type: string
    default: None
    units: m
- key: min_glacier_thick
  name: Min ice depth
  description: Min glacier thickness
  value:
    type: float
    default: '1.0'
    range:
      min: '0.0'
      max: '1000'
    units: '-'
- key: glens_A
  name: Glen's Law param, a
  description: Glen's law exponent
  value:
    type: float
    default: '2.142e-16'
    range:
      min: '0.0'
      max: 3e-15
    units: '-'
- key: B
  name: Glen's Law coeff, B
  description: ', see macgregor (2000)'
  value:
    type: float
    default: '0.0012'
    range:
      min: 1e-3
      max: '0.01'
    units: m/(Pa*yr)
- key: char_sliding_vel
  name: Char. sliding velocity
  description: Characteristic sliding velocity
  value:
    type: float
    default: '10.0'
    range:
      min: '0.0'
      max: '100.0'
    units: '***unitsneeded'
- key: char_tau_bed
  name: Char. bed stress
  description: Characteristic shear stress at the bed
  value:
    type: float
    default: '100000.0'
    range:
      min: '0.0'
      max: 1e6
    units: '****unitsneeded'
- key: depth_to_water_table
  name: Depth to water table
  description: Distance from ice surface to water table
  value:
    type: float
    default: '20.0'
    range:
      min: '0'
      max: '1000.0'
    units: meters
- key: max_float_fraction
  name: Max float fraction
  description: Limits the water level in ice
  value:
    type: float
    default: '80.0'
    range:
      min: '0'
      max: '100.0'
    units: percent
- key: Hp_eff
  name: Hp effective (****)
  description: Effective pressure of water
  value:
    type: float
    default: '20.0'
    range:
      min: '0'
      max: '100.0'
    units: meters
Input 3:
- key: init_ELA
  name: Initial ELA value
  description: Equilibrium line altitude
  value:
    type: float
    default: '3350.0'
    range:
      min: '2500.0'
      max: '4500.0'
    units: meters
- key: ELA_step_size
  name: ELA step size
  description: Ela step size
  value:
    type: float
    default: '-10.0'
    range:
      min: '-100'
      max: '100.0'
    units: meters
- key: ELA_step_interval
  name: ELA step interval
  description: Ela step interval
  value:
    type: float
    default: '500.0'
    range:
      min: '50.0'
      max: '1000.0'
    units: meters
- key: grad_Bz
  name: Mass balance gradient
  description: Mass balance gradient in z
  value:
    type: float
    default: '0.01'
    range:
      min: 1e-3
      max: '0.1'
    units: '***unitsneeded'
- key: max_Bz
  name: Max mass balance
  description: Maximum allowed mass balance
  value:
    type: float
    default: '2.0'
    range:
      min: '1.0'
      max: '10.0'
    units: '***unitsneeded'
- key: spinup_time
  name: Spinup time
  description: Spinup time
  value:
    type: float
    default: '200.0'
    range:
      min: '0.0'
      max: 1e3
    units: years
- key: sea_level
  name: Sea level
  description: Sea level
  value:
    type: float
    default: '-100'
    range:
      min: '-200.0'
      max: '200.0'
    units: meters
- key: Cp_ice
  name: Heat capacity (ice)
  description: Specific heat capacity
  value:
    type: float
    default: '2060.0'
    range:
      min: '2000.0'
      max: '2100.0'
    units: J/(kg*K)
- key: geothermal_heat_flux
  name: Geothermal heat flux
  description: Geothermal heat flux
  value:
    type: float
    default: 1.575e6
    range:
      min: 1e5
      max: 1e7
    units: (J/year)/m^2
- key: geothermal_gradient
  name: Geothermal gradient
  description: Geothermal gradient
  value:
    type: float
    default: '-0.0255'
    range:
      min: '-0.1'
      max: '0.0'
    units: '***deg_C/meter??'
Toggles:
- key: VARIABLE_DT_TOGGLE
  name: Variable dt toggle
  description: Use variable/adaptive timestep (0 = no, 1 = yes)
  value:
    type: int
    default: '1'
    range:
      min: '0'
      max: '1'
    units: '-'
- key: INIT_COND_TOGGLE
  name: Init. condition choice
  description: 0 = ??, 1 = ??, 2 = ??
  value:
    type: int
    default: '1'
    range:
      min: '0'
      max: '1'
    units: '-'
- key: GENERIC_ICE_TOGGLE
  name: Generic ice toggle
  description: Start w/ generic ice surface (0 = no, 1 = yes)
  value:
    type: int
    default: '0'
    range:
      min: '0'
      max: '1'
    units: '-'
- key: ICEFLOW_TOGGLE
  name: Ice flow toggle
  description: Ice motion by deformation (0 = no, 1 = yes)
  value:
    type: int
    default: '1'
    range:
      min: '0'
      max: '1'
    units: '-'
- key: ICESLIDE_TOGGLE
  name: Ice slide toggle
  description: Ice motion by sliding (0 = no, 1 = yes)
  value:
    type: int
    default: '0'
    range:
      min: '0'
      max: '1'
    units: '-'
- key: FREEZE_ON_TOGGLE
  name: Freeze on toggle
  description: Basal ice frozen to bed (0 = no, 1 = yes)
  value:
    type: int
    default: '0'
    range:
      min: '0'
      max: '1'
    units: '-'
- key: MASS_BALANCE_TOGGLE
  name: Mass balance method
  description: Climate scenario
  value:
    type: choice
    default: ELA_LOWERING
    choices:
    - ZERO_BALANCE
    - CONSTANT_ELA
    - ELA_LOWERING
    - ELA_TIME_SERIES
    - EXTERNAL_FUNC
    - ELA_LOWERING2
    - BALANCE_FILE
    - D18O_TIME_SERIES
    units: '-'
- key: WEST_BC_TOGGLE
  name: Western b.c. method
  description: Boundary condition
  value:
    type: choice
    default: ICE_FREE_BOUND
    choices:
    - ICE_FREE_BOUND
    - ZERO_FLUX_BOUND
    - CONST_FLUX_BOUND
    - SURF_ELEV_BOUND
    - SURF_SLOPE_BOUND
    units: '-'
- key: EAST_BC_TOGGLE
  name: Eastern b.c. method
  description: Boundary condition
  value:
    type: choice
    default: ICE_FREE_BOUND
    choices:
    - ICE_FREE_BOUND
    - ZERO_FLUX_BOUND
    - CONST_FLUX_BOUND
    - SURF_ELEV_BOUND
    - SURF_SLOPE_BOUND
    units: '-'
- key: SOUTH_BC_TOGGLE
  name: Southern b.c. method
  description: Boundary condition
  value:
    type: choice
    default: ICE_FREE_BOUND
    choices:
    - ICE_FREE_BOUND
    - ZERO_FLUX_BOUND
    - CONST_FLUX_BOUND
    - SURF_ELEV_BOUND
    - SURF_SLOPE_BOUND
    units: '-'
- key: NORTH_BC_TOGGLE
  name: Northern b.c. method
  description: Boundary condition
  value:
    type: choice
    default: ICE_FREE_BOUND
    choices:
    - ICE_FREE_BOUND
    - ZERO_FLUX_BOUND
    - CONST_FLUX_BOUND
    - SURF_ELEV_BOUND
    - SURF_SLOPE_BOUND
    units: '-'
Output:
- key: save_grid_dt
  name: Save grid dt
  description: Interval to save grids, years
  value:
    type: float
    default: '100.0'
    range:
      min: '1.0'
      max: 1e5
    units: '-'
- key: SAVE_HI_GRIDS
  name: Save Hi grids toggle
  description: Option to save computed hi grids
  value:
    type: choice
    default: 'Yes'
    choices:
    - 'Yes'
    - 'No'
    units: '-'
- key: hi_gs_file
  name: Save Hi grids file
  description: Filename for hi grid stack
  value:
    type: string
    default: '[case_prefix]_2D_iceH.nc'
    units: '-'
- key: SAVE_ZI_GRIDS
  name: Save Zi grids toggle
  description: Option to save computed zi grids
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
    units: '-'
- key: zi_gs_file
  name: Save Zi grids file
  description: Filename for zi grid stack
  value:
    type: string
    default: '[case_prefix]_2D_iceZ.nc'
    units: '-'
- key: SAVE_MR_GRIDS
  name: Save MR grids toggle
  description: Option to save computed mr grids
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
    units: '-'
- key: mr_gs_file
  name: Save MR grids file
  description: Filename for mr grid stack
  value:
    type: string
    default: '[case_prefix]_2D_iceMR.nc'
    units: '-'
- key: save_pixels_dt
  name: Save time series dt
  description: Interval to save time series values, years
  value:
    type: float
    default: '10.0'
    range:
      min: '1.0'
      max: '1000'
    units: '-'
- key: pixel_file
  name: Monitored pixel file
  description: Filename for monitored pixel file
  value:
    type: string
    default: '[case_prefix]_outlets.txt'
    units: '-'
- key: SAVE_HI_PIXELS
  name: Save Hi time series toggle
  description: Option to save computed hi time series
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
    units: '-'
- key: hi_ts_file
  name: Save Hi time series file
  description: Filename for hi time series
  value:
    type: string
    default: '[case_prefix]_0D_iceH.txt'
    units: '-'
- key: SAVE_ZI_PIXELS
  name: Save Zi pixels toggle
  description: Option to save computed zi time series
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
    units: '-'
- key: zi_ts_file
  name: Save Zi time series file
  description: Filename for zi time series
  value:
    type: string
    default: '[case_prefix]_0D_iceZ.txt'
    units: '-'
- key: SAVE_MR_PIXELS
  name: Save MR time series toggle
  description: Option to save computed mr time series
  value:
    type: choice
    default: 'No'
    choices:
    - 'Yes'
    - 'No'
    units: '-'
- key: mr_ts_file
  name: Save MR time series file
  description: Filename for mr time series
  value:
    type: string
    default: '[case_prefix]_0D_iceMR.txt'
    units: '-'
About:
- key: ModelName
  name: Model name
  description: Name of the model
  value:
    type: String
    default: IceGC2D
    units: '-'
- key: ModelAuthor
  name: Author name
  description: Name of the model author
  value:
    type: String
    default: 'Mark Kessler, Eric Hutton, Scott Peckham '
    units: '-'
- key: HTML_HELP_FILE
  name: HTML help file
  description: Url for html help file
  value:
    type: String
    default: http://csdms.colorado.edu/wiki/Model_help:Gc2d
    units: '-'
